### ISSUE TITLE
Failed to connect to unix socket

### ISSUE THREAD

**Issue by MoienBowen** [charlie0129/batt#18] opened 2024-08-28 15:58 UTC
MBA M4, macOS 14.6.1

Installed version via brew:
```
brew info batt
==> batt: stable 0.2.1 (bottled)
Control and limit battery charging on Apple Silicon MacBooks
https://github.com/charlie0129/batt
Installed
/opt/homebrew/Cellar/batt/0.2.1 (7 files, 11.2MB) *
```

Error when setting with batt
```
$ sudo batt limit 80
Password:
ERRO[2024-08-28 17:54:32.433] failed to connect to unix socket. 1) Do you have adequate permissions? Please re-run as root. 2) Is the daemon running? Have installed it?
Error: failed to set limit: failed to send request: Put "http://unix/limit": dial unix /var/run/batt.sock: connect: no such file or directory
Usage:
  batt limit [percentage] [flags]

Flags:
  -h, --help   help for limit

Global Flags:
  -l, --log-level string   log level (trace, debug, info, warn, error, fatal, panic) (default "info")
```

**Comment by charlie0129** [comment] 2024-08-28 16:08
Hi, have you started the homebrew service? I didn't see it in the information you provided.

Or try again with the original installations in README without homwbrew.

**Comment by charlie0129** [comment] 2024-08-28 16:18
Will `brew service start batt` do?

**Comment by charlie0129** [comment] 2024-08-28 16:41
Can you show the content of `/tmp/batt.log`?

**Comment by charlie0129** [comment] 2024-08-28 17:46
It seems homebrew service is having some issues. The service (batt daemon) is not running at all. I personally don't use homebrew on my Mac so some investigation is needed for me to see what is going on.

Is the commandline installation method feasible? In this way it should run as intended.

**Comment by charlie0129** [comment] 2024-10-08 11:25
Homebrew is now officially tested and supported, so closing this issue.

Maybe the lack of **sudo** when starting the service (`sudo brew service start batt`) prevented the batt daemon from running. 

Feel free to open again if this still fails.

**Closed by charlie0129** 2024-10-08 11:25 UTC

**Comment by charlie0129** [comment] 2024-10-08 11:46
> Just one comment, you have a typo there, it should be `services`.

Oops, you are right.

**Comment by PaRr0tBoY** [comment] 2024-10-25 10:48
`sudo brew service start batt`
`sudo batt limit 80`
Commands above works,thanks
